VIA_ENABLE = no
ENCODER_MAP_ENABLE = false
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
CONSOLE_ENABLE = yes
OS_DETECTION_ENABLE = no
BOOTMAGIC_ENABLE = full
TAP_DANCE_ENABLE = yes
AUTO_SHIFT_ENABLE = no